/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ConDataHora;
import Controle.ConFucoesPrincipais;
import Controle.ConManipulaArquivo;
import Controle.ConUtil;
import java.awt.Dimension;
import java.util.Properties;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author jaguar
 */
public class TelaPdv extends javax.swing.JInternalFrame {
    AreaPadrao area;
    
    ConUtil util;
    ConManipulaArquivo mani;
    ConDataHora dataHora;
    ConFucoesPrincipais fuPrinc;
    
    Thread tDataHora;
    Thread tConFuncoes;
    
    Properties pros;

    public String getjLData() {
        return jLData.getText();
    }

    public void setjLData(String jLData) {
        this.jLData.setText(jLData);
    }

    public String getjLHora() {
        return jLHora.getText();
    }

    public void setjLHora(String jLHora) {
        this.jLHora.setText(jLHora);
    }

    public String getjLProdutos() {
        return jLProdutos.getText();
    }

    public void setjLProdutos(String jLProdutos) {
        this.jLProdutos.setText(jLProdutos);
    }

    public String getjLEstado() {
        return jLEstado.getText();
    }

    public void setjLEstado(String jLEstado) {
        this.jLEstado.setText(jLEstado);
    }

    public String getjLStatus() {
        return jLStatus.getText();
    }

    public void setjLStatus(String jLStatus) {
        this.jLStatus.setText(jLStatus);
    }

    public JTextField getjTEntrada() {
        return jTEntrada;
    }

    public void setjTEntrada(int opcao) {
        switch (opcao) {
            case 0: 
                this.jTEntrada.setEditable(false); 
                break;
            case 1: 
                this.jTEntrada.setEditable(true);
                this.jTEntrada.requestFocus();
                break;
            default: this.jTEntrada.setEditable(true);
        }
        
    }
    
    
    
    /**
     * Creates new form TelaPdv
     */
    public TelaPdv(AreaPadrao area) {
        initComponents();
        this.area = area;
        util = new ConUtil();
        mani = new ConManipulaArquivo();
        
        /*Inicializa o banco de dados.*/
        fuPrinc = new ConFucoesPrincipais(this);
        tConFuncoes = new Thread(fuPrinc);
        tConFuncoes.start();
        
        
        /*Atualiza data e hora em tempo real*/
        dataHora = new ConDataHora(this);
        tDataHora = new Thread(dataHora);
        tDataHora.start();
      
        /* Inicialização das Variaveis*/
        jLErro.setText("");
        jLMOperador.setText("");
        jLMVendedor.setText("");
        jLNOperador.setText("");
        jLNVendedor.setText("");
        jTEntrada.setText("");
        jLStatus.setText("");
        jLProdutos.setText("");
        jTAProdutos.setFocusable(false);
        jTAProdutos.enableInputMethods(false);
        jTEntrada.requestFocus();
        jLIp.setText(util.getIP());
        
        pros = mani.getProp();
        jLTitulo.setText(pros.getProperty("Titulo"));
        jLLoja.setText(pros.getProperty("Filial"));
        jLCaixa.setText(pros.getProperty("Caixa"));
        
    }
    
    public void setPosicao() {  
        Dimension d = this.area.getPreferredSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2); 
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLProdutos = new javax.swing.JLabel();
        jTEntrada = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLNOperador = new javax.swing.JLabel();
        jLNVendedor = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLIp = new javax.swing.JLabel();
        jLTitulo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLLoja = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLCaixa = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLData = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLHora = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAProdutos = new javax.swing.JTextArea();
        jLMOperador = new javax.swing.JLabel();
        jLMVendedor = new javax.swing.JLabel();
        jLEstado = new javax.swing.JLabel();
        jLStatus = new javax.swing.JLabel();
        jLErro = new javax.swing.JLabel();
        jPImagens = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(209, 218, 218));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLProdutos.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLProdutos.setForeground(new java.awt.Color(55, 24, 220));
        jLProdutos.setText("Informações do produto");
        jPanel1.add(jLProdutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 1010, 60));

        jTEntrada.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jTEntrada.setForeground(new java.awt.Color(55, 24, 220));
        jTEntrada.setText("jTextField1");
        jPanel1.add(jTEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 579, 470, -1));

        jLabel2.setForeground(new java.awt.Color(55, 24, 220));
        jLabel2.setText("Operador:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 530, 80, 40));

        jLabel3.setForeground(new java.awt.Color(55, 24, 220));
        jLabel3.setText("Vendedor:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 573, 70, 50));

        jLNOperador.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLNOperador.setText("jLabel4");
        jPanel1.add(jLNOperador, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 530, 340, 40));

        jLNVendedor.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLNVendedor.setText("jLabel5");
        jPanel1.add(jLNVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 570, 340, 50));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Computador:");

        jLIp.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLIp.setText("132.1");

        jLTitulo.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLTitulo.setForeground(new java.awt.Color(55, 24, 220));
        jLTitulo.setText("ant'Ana S/A Drogaria,");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Loja:");

        jLLoja.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLLoja.setText("001");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Caixa:");

        jLCaixa.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLCaixa.setText("01");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("Data:");

        jLData.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLData.setText("29/12/2016");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("Hora:");

        jLHora.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLHora.setText("11:20:32");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setText("Verão");

        jLabel15.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(179, 19, 19));
        jLabel15.setText("Verão");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLIp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLLoja, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(jLCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLData, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLHora, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLIp, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
            .addComponent(jLTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLLoja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLHora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, -1));

        jTAProdutos.setColumns(20);
        jTAProdutos.setRows(5);
        jScrollPane1.setViewportView(jTAProdutos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 60, 420, 470));

        jLMOperador.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLMOperador.setText("jLabel6");
        jPanel1.add(jLMOperador, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 530, 110, 40));

        jLMVendedor.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLMVendedor.setText("jLabel7");
        jPanel1.add(jLMVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 580, 100, 40));

        jLEstado.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLEstado.setForeground(new java.awt.Color(199, 24, 24));
        jLEstado.setText("Caixa Fechado.");
        jPanel1.add(jLEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 470, 30));

        jLStatus.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLStatus.setForeground(new java.awt.Color(55, 24, 220));
        jLStatus.setText("Status");
        jPanel1.add(jLStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 470, 40));

        jLErro.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLErro.setForeground(new java.awt.Color(55, 24, 220));
        jLErro.setText("Informativos");
        jPanel1.add(jLErro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 470, 40));

        jPImagens.setPreferredSize(new java.awt.Dimension(590, 385));

        jLabel4.setIcon(new javax.swing.ImageIcon("/home/jaguar/Imagens/java.jpg")); // NOI18N
        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout jPImagensLayout = new javax.swing.GroupLayout(jPImagens);
        jPImagens.setLayout(jPImagensLayout);
        jPImagensLayout.setHorizontalGroup(
            jPImagensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 590, Short.MAX_VALUE)
        );
        jPImagensLayout.setVerticalGroup(
            jPImagensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 385, Short.MAX_VALUE)
        );

        jPanel1.add(jPImagens, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 590, 385));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLCaixa;
    private javax.swing.JLabel jLData;
    private javax.swing.JLabel jLErro;
    private javax.swing.JLabel jLEstado;
    private javax.swing.JLabel jLHora;
    private javax.swing.JLabel jLIp;
    private javax.swing.JLabel jLLoja;
    private javax.swing.JLabel jLMOperador;
    private javax.swing.JLabel jLMVendedor;
    private javax.swing.JLabel jLNOperador;
    private javax.swing.JLabel jLNVendedor;
    private javax.swing.JLabel jLProdutos;
    private javax.swing.JLabel jLStatus;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPImagens;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTAProdutos;
    private javax.swing.JTextField jTEntrada;
    // End of variables declaration//GEN-END:variables
    
}
